version: "3.8"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb:27017/weathermap
      - PYTHONPATH=/app
  test:
    build: .
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb:27017/weathermap
      - PYTHONPATH=/app
    command: pytest
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
